### PR TITLE
Update permissions to allow execution using ./deployVersion.sh

### PR DESCRIPTION
**Pull request by purple-waves**
Initial version does not allow execution using the ./ notation, this was an oversight

### CODE REVIEW

**Review by roroross — COMMENTED** [review]
im confused.. is this file "./deployVersion.sh" supposed to be a empty file?

**Comment by purple-waves** [comment]
The file isn't actually empty, it's just weird because the thing that I changed was permissions. The contents can be viewed here https://github.com/googleinterns/step269-2020/blob/versioningScript/deployVersion.sh

**Comment by roroross** [comment]
yep i had a read.

**Review by roroross — APPROVED** [review]
lgtm

**Review by sbland-g — APPROVED** [review]

**Pull request merged**
